# Server configuration
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.saveetha.campusconnect=DEBUG

# Firebase configuration
firebase.project-id=campus-connect-a6aa5
firebase.database-url=https://campus-connect-a6aa5-default-rtdb.firebaseio.com
firebase.config-path=src/main/resources/serviceAccountKey.json
